name: Build and Deploy Python App to Azure Web App - cic-agasthya

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering
    inputs:
      branch:
        description: 'Branch to deploy'
        default: 'main'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Ensure you're using the latest version

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: List files in the repository
        run: ls -la  # Check if requirements.txt exists

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt  # Ensure requirements.txt exists

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for JWT requests

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BA9AB7933C9142A7BC06516FA8A3BE4F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_061C75D953634DF2965077D244EC759C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_363EB4E8D3454E72B0824C91E61140D7 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'cic-agasthya'
          slot-name: 'Production'
