name: Install Dependencies

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: List files in the repository to check if requirements.txt exists
      - name: List files
        run: ls -la

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
